#!/bin/bash


echo  Hello, what is your name, stranger?
read who
echo Nice to meet you, $who!
echo "***********************"
echo  How old are you, $who?
read age
echo So, $who is $age years old now.
echo "***********************"
echo Bye, $who!

