#!/bin/bash
echo -n "Hello, what is your name, stranger: " 
read who
echo Nice to meet you, $who!
sleep 1
echo -n "How old are you: "
read age

if [ $age -lt 21 ]
then
  echo "You're too yound for beer, $who!"
else
  echo "Take your beer, $who!"
fi

echo bye!
