---
cumulus:
  interfaces:
    - device: lo
    
    - device: eth0
      v4: 172.16.0.12/24
      vrf: mgmt
      args: "{{ eth0_shared_args }}"

    - device: mgmt
      v4: 127.0.0.1/8
      v6: ::1/128
      args:
        - vrf-table auto

    - device: swp[1-7]

    - device: swp8
      args:
        - bridge-access 5 

    - device: bond0
      v4: 10.1.0.2/30
      mtu: 1500
      args:
        - bond-slaves glob swp5-6
        - bond-xmit-hash-policy layer3+4
        - bond-mode 802.3ad
        - bond-miimon 100
        - bond-lacp-rate 1
        - bond-min-links 1

    - device: bridge
      args:
        - bridge-vlan-aware yes
        - bridge-stp yes
        - bridge-vids 9 5
        - bridge-pvid 1
        - bridge-ports swp1 swp8

    - device: bridge.5
      v4: 10.5.0.2/24

    - device: bridge.9
      v4: 10.9.0.2/24

frr_daemons:
  zebra: true
  bgpd: true
  ospfd: true
  bfdd: false
frr_interfaces:
  bond0:
    other:
      - "ip ospf mtu-ignore"
      - "ip ospf network point-to-point"
frr_router_id: 10.5.0.2
frr_bgp:
  asns:
    1:
      log_neighbor_changes: true
      no_ebgp_requires_policy: true
      neighbors:
        10.5.0.1:
          asn: 1
          default_originate: false
          af_v4:
            - "soft-reconfiguration inbound"
      redistribute:
        - connected
        - ospf
frr_ospf:
  areas:
    0:
      networks:
        - "10.1.0.2/32"
  log_adjacency_changes: true
  redistribute:
    - bgp
    - connected
