---
- name: Setup Cumulus Interfaces
  hosts: cumulus
  become: true

  tasks:
    - name: Interfaces template
      template:
        src: templates/interfaces.j2
        dest: /etc/network/interfaces
      notify: ifup

  handlers:
    - name: ifup
      shell: ifup -a
