- name: Cisco ASA access-list config
  connection: local
  gather_facts: false
  hosts: rtr-routers
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username:          #######
      password:          #######
      transport: cli
      authorize: yes
      auth_pass:         #######
  tasks:
    - name: create object group
      asa_config:
        lines:
          - network-object host 10.1.0.1
          - network-object host 10.1.0.2
          - network-object host 10.1.0.3
        parents: ['object-group network dummy-group']
        provider: "{{ cli }}"
        authorize: yes
        context: infra
      register: result

    - name: configure access-list
      asa_acl:
        lines:
          - access-list acl_dummy extended permit tcp object-group dummy-group any eq www
          - access-list acl_dummy extended permit udp object-group dummy-group any eq domain
          - access-list acl_dummy extended deny ip any any
        before: clear configure access-list acl_inside
        match: strict
        replace: block
        authorize: yes
        context: infra
        provider: "{{ cli }}" 
#     register: result

    - debug: var=result

